"""add external_message_id dedup key to ingestion tasks

Revision ID: 0ebd5e9cf387
Revises: 8c2b0cf074ff
Create Date: 2026-07-29 01:27:06.201053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ebd5e9cf387'
down_revision: Union[str, Sequence[str], None] = '8c2b0cf074ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: unrelated pre-existing schema drift (dangling FK constraints on
    # chats/files/personas, missing indexes/unique constraints on classrooms/documents)
    # detected by autogenerate has been pruned from this migration — see the same note
    # in 8c2b0cf074ff_add_ai_support_ticket_system_tables.py.
    with op.batch_alter_table("ingestion_tasks") as batch_op:
        batch_op.add_column(sa.Column("external_message_id", sa.String(), nullable=True))
        batch_op.create_unique_constraint(
            "uq_ingestion_task_dedup", ["task_type", "source_id", "external_message_id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ingestion_tasks") as batch_op:
        batch_op.drop_constraint("uq_ingestion_task_dedup", type_="unique")
        batch_op.drop_column("external_message_id")
    # ### end Alembic commands ###
