"""Add person_id to Feature model

Revision ID: 63414beb10fb
Revises: e193e109b107
Create Date: 2025-12-24 19:38:31.120097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63414beb10fb'
down_revision: Union[str, Sequence[str], None] = 'e193e109b107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.Integer(), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.alter_column('name',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.create_index(batch_op.f('ix_features_name'), ['name'], unique=True)
        batch_op.create_foreign_key('fk_features_person_id', 'personas', ['person_id'], ['id'])

    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.drop_column('feature_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feature_id', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_constraint('fk_features_person_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_features_name'))
        batch_op.alter_column('name',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.drop_column('person_id')
    # ### end Alembic commands ###
