"""add ai support ticket system tables

Revision ID: 8c2b0cf074ff
Revises: 838b44bdbb43
Create Date: 2026-07-29 01:06:16.029458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c2b0cf074ff'
down_revision: Union[str, Sequence[str], None] = '838b44bdbb43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adapter_cursors',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('cursor_value', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('adapter_outbox_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('external_message_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('normalized_payload', sa.JSON(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_message_id', name='uq_outbox_source_external_message')
    )
    op.create_index(op.f('ix_adapter_outbox_messages_conversation_id'), 'adapter_outbox_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_adapter_outbox_messages_source_id'), 'adapter_outbox_messages', ['source_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('unit_serial', sa.String(), nullable=True),
    sa.Column('issue_description', sa.String(), nullable=True),
    sa.Column('question_round_count', sa.Integer(), nullable=False),
    sa.Column('serial_correction_attempt_count', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'conversation_id', name='uq_conversation_source_conversation_id')
    )
    op.create_index(op.f('ix_conversations_conversation_id'), 'conversations', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversations_source_id'), 'conversations', ['source_id'], unique=False)
    op.create_table('gmail_watches',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('history_id', sa.String(), nullable=True),
    sa.Column('watch_expiration', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('ingestion_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_tasks_conversation_id'), 'ingestion_tasks', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ingestion_tasks_status'), 'ingestion_tasks', ['status'], unique=False)
    op.create_index('ix_ingestion_tasks_status_conversation', 'ingestion_tasks', ['status', 'conversation_id'], unique=False)
    op.create_index(op.f('ix_ingestion_tasks_task_type'), 'ingestion_tasks', ['task_type'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('external_message_id', sa.String(), nullable=True),
    sa.Column('sender_address', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('body_text', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('synced_to_ticket_log', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_table('pending_log_syncs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('conversation_message_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_message_id'], ['conversation_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_log_syncs_ticket_id'), 'pending_log_syncs', ['ticket_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE: autogenerate also detected pre-existing schema drift unrelated to this
    # feature (dangling FK constraints on chats/files/personas left over from the
    # users-table drop, and missing indexes/unique constraints on classrooms/documents).
    # Left untouched here deliberately — that's a separate cleanup, not part of the
    # AI support ticket system.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_log_syncs_ticket_id'), table_name='pending_log_syncs')
    op.drop_table('pending_log_syncs')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_ingestion_tasks_task_type'), table_name='ingestion_tasks')
    op.drop_index('ix_ingestion_tasks_status_conversation', table_name='ingestion_tasks')
    op.drop_index(op.f('ix_ingestion_tasks_status'), table_name='ingestion_tasks')
    op.drop_index(op.f('ix_ingestion_tasks_conversation_id'), table_name='ingestion_tasks')
    op.drop_table('ingestion_tasks')
    op.drop_table('gmail_watches')
    op.drop_index(op.f('ix_conversations_source_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_conversation_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_adapter_outbox_messages_source_id'), table_name='adapter_outbox_messages')
    op.drop_index(op.f('ix_adapter_outbox_messages_conversation_id'), table_name='adapter_outbox_messages')
    op.drop_table('adapter_outbox_messages')
    op.drop_table('adapter_cursors')
    # ### end Alembic commands ###
