"""add_store_id_to_feature

Revision ID: 8c4b376c6ba4
Revises: 98f3090a1770
Create Date: 2026-03-11 06:06:39.627317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c4b376c6ba4'
down_revision: Union[str, Sequence[str], None] = '98f3090a1770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('features', sa.Column('store_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('features', 'store_id')
    # ### end Alembic commands ###
