"""add classroom tables

Revision ID: 96c3562d3680
Revises: c9f1a2b3d4e5
Create Date: 2026-04-15 23:44:42.600353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c3562d3680'
down_revision: Union[str, Sequence[str], None] = 'c9f1a2b3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classrooms_id'), 'classrooms', ['id'], unique=False)
    op.create_table('classroom_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('classroom_id', sa.String(length=36), nullable=False),
    sa.Column('inventory_item_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classroom_items_id'), 'classroom_items', ['id'], unique=False)
    op.create_index(op.f('ix_classroom_items_inventory_item_id'), 'classroom_items', ['inventory_item_id'], unique=True)
    op.create_table('classroom_item_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('inventory_item_document_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['classroom_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classroom_item_documents_id'), 'classroom_item_documents', ['id'], unique=False)
    op.create_index(op.f('ix_classroom_item_documents_inventory_item_document_id'), 'classroom_item_documents', ['inventory_item_document_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classroom_item_documents_inventory_item_document_id'), table_name='classroom_item_documents')
    op.drop_index(op.f('ix_classroom_item_documents_id'), table_name='classroom_item_documents')
    op.drop_table('classroom_item_documents')
    op.drop_index(op.f('ix_classroom_items_inventory_item_id'), table_name='classroom_items')
    op.drop_index(op.f('ix_classroom_items_id'), table_name='classroom_items')
    op.drop_table('classroom_items')
    op.drop_index(op.f('ix_classrooms_id'), table_name='classrooms')
    op.drop_table('classrooms')
    # ### end Alembic commands ###
