"""Rename person_id to person-id in Feature model

Revision ID: e06228026ca6
Revises: 63414beb10fb
Create Date: 2025-12-24 19:49:51.216383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e06228026ca6'
down_revision: Union[str, Sequence[str], None] = '63414beb10fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('persona_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_features_person_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_features_persona_id', 'personas', ['persona_id'], ['id'])
        batch_op.drop_column('person_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_features_persona_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_features_person_id', 'personas', ['person_id'], ['id'])
        batch_op.drop_column('persona_id')
    # ### end Alembic commands ###
